/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.umich.cailab;

import com.google.gson.Gson;
import ij.plugin.PlugIn;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLConnection;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.locks.*;

/**
 *
 * @author loganaw
 */
public class StageControl extends javax.swing.JFrame implements PlugIn {

    private Lock http_lock;

    public static void print_error(String err) {
        System.err.println(err);
    }

    public static byte[] read_all_buffer(InputStream is) throws IOException {
        ByteArrayOutputStream buffer = new ByteArrayOutputStream();
        int nRead = 0;
        byte[] data = new byte[4096];
        while ((nRead = is.read(data)) != -1) {
            buffer.write(data, 0, nRead);
        }
        is.close();
        buffer.flush();
        return buffer.toByteArray();
    }

    public String get_http(String url) {
        byte[] targetArray;
        try {
            this.http_lock.lock();
            URL server_url;
            try {
                server_url = new URL(url);
            } catch (MalformedURLException ex) {
                print_error("Malformed URL Exception found.");
                return "ERROR";
            }
            URLConnection conn;
            try {
                conn = server_url.openConnection();
                InputStream is = conn.getInputStream();
                targetArray = read_all_buffer(is);
            } catch (IOException ex) {
                print_error("IO Exception found.");
                return "ERROR";
            }
        } finally {
            this.http_lock.unlock();
        }

        //System.out.println("Total data read: " + targetArray.length);
        //System.out.println("\tEx: " + targetArray[0] + ", " + targetArray[1] + ", " + targetArray[2]);
        return new String(targetArray, StandardCharsets.UTF_8);
    }

    public static Map<?, ?> parse_json(String input) {
        Gson gson = new Gson();
        return gson.fromJson(input, Map.class);
    }

    /**
     * Creates new form StageControl
     */
    public StageControl() {
        initComponents();
        current_positions = new HashMap<>();
        current_positions.put(1, 0.0);
        current_positions.put(2, 0.0);
        current_positions.put(3, 0.0);

        this.http_lock = new ReentrantLock();

        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jFrame1 = new javax.swing.JFrame();
        jSlider1 = new javax.swing.JSlider();
        jTextField1 = new javax.swing.JTextField();
        jSlider2 = new javax.swing.JSlider();
        jTextField2 = new javax.swing.JTextField();
        jSlider3 = new javax.swing.JSlider();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        yGoText = new javax.swing.JTextField();
        xGoText = new javax.swing.JTextField();
        zGoText = new javax.swing.JTextField();
        xGoButton = new javax.swing.JButton();
        yGoButton = new javax.swing.JButton();
        zGoButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        MoreLeftButton = new javax.swing.JButton();
        LeftButton = new javax.swing.JButton();
        RightButton = new javax.swing.JButton();
        MoreRightButton = new javax.swing.JButton();
        MoreUpButton = new javax.swing.JButton();
        TopButton = new javax.swing.JButton();
        DownButton = new javax.swing.JButton();
        MoreDownButton = new javax.swing.JButton();
        MoreZDownButton = new javax.swing.JButton();
        ZDownButton = new javax.swing.JButton();
        ZUpButton = new javax.swing.JButton();
        MoreZUpButton = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        bigStepText = new javax.swing.JTextField();
        smallStepText = new javax.swing.JTextField();
        ModeSelectText = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(320, 420));
        setMinimumSize(new java.awt.Dimension(320, 420));
        setPreferredSize(new java.awt.Dimension(320, 420));

        jSlider1.setMaximum(25);
        jSlider1.setValue(0);
        jSlider1.setEnabled(false);

        jTextField1.setEditable(false);
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField1.setText("jTextField1");
        jTextField1.setFocusTraversalKeysEnabled(false);
        jTextField1.setFocusable(false);
        jTextField1.setMaximumSize(new java.awt.Dimension(80, 23));
        jTextField1.setMinimumSize(new java.awt.Dimension(80, 23));
        jTextField1.setPreferredSize(new java.awt.Dimension(80, 23));

        jSlider2.setMaximum(50);
        jSlider2.setMinimum(-50);
        jSlider2.setValue(0);
        jSlider2.setEnabled(false);

        jTextField2.setEditable(false);
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField2.setText("jTextField1");
        jTextField2.setMaximumSize(new java.awt.Dimension(80, 23));
        jTextField2.setMinimumSize(new java.awt.Dimension(80, 23));
        jTextField2.setPreferredSize(new java.awt.Dimension(80, 23));

        jSlider3.setMaximum(50);
        jSlider3.setMinimum(-50);
        jSlider3.setValue(0);
        jSlider3.setEnabled(false);

        jTextField3.setEditable(false);
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField3.setText("jTextField1");
        jTextField3.setFocusTraversalKeysEnabled(false);
        jTextField3.setFocusable(false);
        jTextField3.setMaximumSize(new java.awt.Dimension(80, 23));
        jTextField3.setMinimumSize(new java.awt.Dimension(80, 23));
        jTextField3.setPreferredSize(new java.awt.Dimension(80, 23));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setText("X");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel2.setText("Y");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel3.setText("Z");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel4.setText("X");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel5.setText("Y");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel6.setText("Z");

        yGoText.setText("0");

        xGoText.setText("0");

        zGoText.setText("0");

        xGoButton.setText("GO");
        xGoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xGoButtonActionPerformed(evt);
            }
        });

        yGoButton.setText("GO");
        yGoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yGoButtonActionPerformed(evt);
            }
        });

        zGoButton.setText("GO");
        zGoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zGoButtonActionPerformed(evt);
            }
        });

        MoreLeftButton.setBackground(new java.awt.Color(204, 204, 255));
        MoreLeftButton.setText("<<");
        MoreLeftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoreLeftButtonActionPerformed(evt);
            }
        });

        LeftButton.setBackground(new java.awt.Color(204, 204, 255));
        LeftButton.setText("<<");
        LeftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeftButtonActionPerformed(evt);
            }
        });

        RightButton.setBackground(new java.awt.Color(204, 204, 255));
        RightButton.setText(">>");
        RightButton.setToolTipText("");
        RightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RightButtonActionPerformed(evt);
            }
        });

        MoreRightButton.setBackground(new java.awt.Color(204, 204, 255));
        MoreRightButton.setText(">>");
        MoreRightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoreRightButtonActionPerformed(evt);
            }
        });

        MoreUpButton.setBackground(new java.awt.Color(204, 204, 255));
        MoreUpButton.setText("∧∧");
        MoreUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoreUpButtonActionPerformed(evt);
            }
        });

        TopButton.setBackground(new java.awt.Color(204, 204, 255));
        TopButton.setText("∧∧");
        TopButton.setToolTipText("");
        TopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TopButtonActionPerformed(evt);
            }
        });

        DownButton.setBackground(new java.awt.Color(204, 204, 255));
        DownButton.setText("∨∨");
        DownButton.setToolTipText("");
        DownButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownButtonActionPerformed(evt);
            }
        });

        MoreDownButton.setBackground(new java.awt.Color(204, 204, 255));
        MoreDownButton.setText("∨∨");
        MoreDownButton.setToolTipText("");
        MoreDownButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoreDownButtonActionPerformed(evt);
            }
        });

        MoreZDownButton.setBackground(new java.awt.Color(204, 255, 204));
        MoreZDownButton.setText("∨∨");
        MoreZDownButton.setToolTipText("");
        MoreZDownButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoreZDownButtonActionPerformed(evt);
            }
        });

        ZDownButton.setBackground(new java.awt.Color(204, 255, 204));
        ZDownButton.setText("∨∨");
        ZDownButton.setToolTipText("");
        ZDownButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZDownButtonActionPerformed(evt);
            }
        });

        ZUpButton.setBackground(new java.awt.Color(204, 255, 204));
        ZUpButton.setText("∧∧");
        ZUpButton.setToolTipText("");
        ZUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZUpButtonActionPerformed(evt);
            }
        });

        MoreZUpButton.setBackground(new java.awt.Color(204, 255, 204));
        MoreZUpButton.setText("∧∧");
        MoreZUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoreZUpButtonActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OFF", "small", "large" }));

        bigStepText.setText("1.0");

        smallStepText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        smallStepText.setText("0.1");

        ModeSelectText.setText("Keyboard Mode");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(xGoButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(xGoText, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(yGoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(yGoText, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(zGoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(zGoText, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSlider1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jSlider2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MoreLeftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LeftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ModeSelectText)
                            .addComponent(bigStepText, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(smallStepText, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MoreUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(RightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(DownButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MoreDownButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MoreZUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ZUpButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ZDownButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MoreZDownButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MoreRightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(yGoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xGoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zGoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xGoButton)
                    .addComponent(yGoButton)
                    .addComponent(zGoButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MoreZUpButton)
                    .addComponent(MoreUpButton)
                    .addComponent(bigStepText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZUpButton)
                    .addComponent(TopButton)
                    .addComponent(smallStepText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MoreLeftButton)
                    .addComponent(LeftButton)
                    .addComponent(RightButton)
                    .addComponent(MoreRightButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DownButton)
                    .addComponent(ZDownButton)
                    .addComponent(ModeSelectText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MoreDownButton)
                    .addComponent(MoreZDownButton)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void xGoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xGoButtonActionPerformed
        // X
        String new_val = xGoText.getText();
        try {
            Double.parseDouble(new_val);
        } catch (NumberFormatException e) {
            return;
        }
        get_http("http://10.156.2.107:5000/move/2/" + new_val);
    }//GEN-LAST:event_xGoButtonActionPerformed

    private void yGoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yGoButtonActionPerformed
        // Y
        String new_val = yGoText.getText();
        try {
            Double.parseDouble(new_val);
        } catch (NumberFormatException e) {
            return;
        }
        get_http("http://10.156.2.107:5000/move/3/" + new_val);
    }//GEN-LAST:event_yGoButtonActionPerformed

    private void zGoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zGoButtonActionPerformed
        // Z
        String new_val = zGoText.getText();
        try {
            Double.parseDouble(new_val);
        } catch (NumberFormatException e) {
            return;
        }
        get_http("http://10.156.2.107:5000/move/1/" + new_val);
    }//GEN-LAST:event_zGoButtonActionPerformed

    private void MoreLeftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoreLeftButtonActionPerformed
        update_positions();
    }//GEN-LAST:event_MoreLeftButtonActionPerformed

    private void LeftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeftButtonActionPerformed
        update_positions();
    }//GEN-LAST:event_LeftButtonActionPerformed

    private void RightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RightButtonActionPerformed
        update_positions();
    }//GEN-LAST:event_RightButtonActionPerformed

    private void MoreRightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoreRightButtonActionPerformed
        update_positions();
    }//GEN-LAST:event_MoreRightButtonActionPerformed

    private void MoreUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoreUpButtonActionPerformed
        update_positions();
    }//GEN-LAST:event_MoreUpButtonActionPerformed

    private void TopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TopButtonActionPerformed
        update_positions();
    }//GEN-LAST:event_TopButtonActionPerformed

    private void DownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownButtonActionPerformed
        update_positions();
    }//GEN-LAST:event_DownButtonActionPerformed

    private void MoreDownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoreDownButtonActionPerformed
        update_positions();
    }//GEN-LAST:event_MoreDownButtonActionPerformed

    private void MoreZDownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoreZDownButtonActionPerformed
        try {
            double step = this.get_big_step_size() * -1.0;
            this.step_axis(1, step, 0, 25);
        } catch (NumberFormatException e) {
            return;
        }
    }//GEN-LAST:event_MoreZDownButtonActionPerformed

    private void ZDownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZDownButtonActionPerformed
        try {
            double step = this.get_step_size() * -1.0;
            this.step_axis(1, step, 0, 25);
        } catch (NumberFormatException e) {
            return;
        }
    }//GEN-LAST:event_ZDownButtonActionPerformed

    private void ZUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZUpButtonActionPerformed
        try {
            double step = this.get_step_size();
            this.step_axis(1, step, 0, 25);
        } catch (NumberFormatException e) {
            return;
        }
    }//GEN-LAST:event_ZUpButtonActionPerformed

    private void MoreZUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoreZUpButtonActionPerformed
        try {
            double step = this.get_big_step_size();
            this.step_axis(1, step, 0, 25);
        } catch (NumberFormatException e) {
            return;
        }
    }//GEN-LAST:event_MoreZUpButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StageControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StageControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StageControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StageControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        StageControl window = new StageControl();
        window.run("");
    }

    @Override
    public void run(String string) {
        System.out.println("Starting StageControl.");

        while (true) {
            this.update_positions();
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
            }
        }
    }

    public void step_axis(int axis, double step, double min, double max) {
        update_positions();
        double new_step = current_positions.get(axis) + step;
        if (new_step <= min) {
            new_step = min;
        }
        if (new_step >= max) {
            new_step = max;
        }
        this.change_axis(axis, new_step);
    }

    public void change_axis(int axis, double val) {
        String val_fmt = String.format("%.5g%n", val);
        get_http("http://10.156.2.107:5000/move/" + axis + "/" + val_fmt);
    }

    public void update_positions() {
        String positions = get_http("http://10.156.2.107:5000/get_positions");
        Map<?, ?> positions_map = parse_json(positions);
        for (Map.Entry<?, ?> entry : positions_map.entrySet()) {
            int k = Integer.parseInt((String) entry.getKey());
            double v = (double) entry.getValue();
            current_positions.replace(k, v);
        }
        System.out.println("New positions = " + current_positions);

        jSlider1.setValue((int) Math.round(current_positions.get(1)));
        jSlider2.setValue((int) Math.round(current_positions.get(3)));
        jSlider3.setValue((int) Math.round(current_positions.get(2)));

        jTextField1.setText(String.valueOf(current_positions.get(1)));
        jTextField2.setText(String.valueOf(current_positions.get(3)));
        jTextField3.setText(String.valueOf(current_positions.get(2)));
    }

    public double get_step_size() throws NumberFormatException {
        String new_val = smallStepText.getText();
        return Double.parseDouble(new_val);
    }

    public double get_big_step_size() throws NumberFormatException {
        String new_val = bigStepText.getText();
        return Double.parseDouble(new_val);
    }

    private Map<Integer, Double> current_positions;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DownButton;
    private javax.swing.JButton LeftButton;
    private javax.swing.JLabel ModeSelectText;
    private javax.swing.JButton MoreDownButton;
    private javax.swing.JButton MoreLeftButton;
    private javax.swing.JButton MoreRightButton;
    private javax.swing.JButton MoreUpButton;
    private javax.swing.JButton MoreZDownButton;
    private javax.swing.JButton MoreZUpButton;
    private javax.swing.JButton RightButton;
    private javax.swing.JButton TopButton;
    private javax.swing.JButton ZDownButton;
    private javax.swing.JButton ZUpButton;
    private javax.swing.JTextField bigStepText;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSlider jSlider3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField smallStepText;
    private javax.swing.JButton xGoButton;
    private javax.swing.JTextField xGoText;
    private javax.swing.JButton yGoButton;
    private javax.swing.JTextField yGoText;
    private javax.swing.JButton zGoButton;
    private javax.swing.JTextField zGoText;
    // End of variables declaration//GEN-END:variables
}
